version: '3.8'

services:
  soc-dashboard:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./logs:/app/logs
      - ./exports:/app/exports
    environment:
      - PYTHONPATH=/app
      - ELK_HOST=elasticsearch
      - WAZUH_HOST=wazuh
    depends_on:
      - elasticsearch
      - wazuh
    restart: unless-stopped
    networks:
      - soc-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - es-data:/usr/share/elasticsearch/data
    networks:
      - soc-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - soc-network

  wazuh:
    image: wazuh/wazuh-manager:4.7.0
    ports:
      - "55000:55000"
      - "1514:1514"
      - "1515:1515"
    environment:
      - WAZUH_MANAGER_CONF_FILE=/wazuh-config-mount/wazuh_manager.conf
    volumes:
      - wazuh-data:/var/ossec/data
    networks:
      - soc-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - soc-network

volumes:
  es-data:
  wazuh-data:
  redis-data:

networks:
  soc-network:
    driver: bridge